# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - main: .
    binary: do-ansible-inventory
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
